highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


url: https://objectiflibre.github.io/
baseurl: /cloudkitty.io/
title: CloudKitty
author: CloudKitty
description: CloudKitty
avatar: cloudkitty.png

defaults:
  - values:
      thumbnail: /assets/defaults/thumbnail.png

theme: jekyll-theme-cayman